# Generated by Django 3.2 on 2023-07-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('description', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('OS', models.CharField(choices=[('1', 'Windows'), ('2', 'Linux'), ('3', 'macOS'), ('4', 'iOS'), ('5', 'Android')], max_length=1)),
                ('CPU', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('0', 'Normal'), ('1', 'Offline'), ('2', 'Error')], default='0', max_length=1)),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('IP', models.CharField(max_length=15)),
                ('can_run_cuda', models.BooleanField(default=False)),
                ('description', models.TextField(default='', max_length=100)),
                ('core_num', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('is_administrator', models.BooleanField(default=False)),
                ('register_time', models.DateField()),
                ('signature', models.TextField(default='', max_length=100)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=20, null=True)),
                ('gender', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(null=True)),
                ('accuracy', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.dataset')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.device')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.model')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.user')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.user'),
        ),
    ]
