# Generated by Django 3.2 on 2023-07-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='bandwidth',
            new_name='max_bandwidth',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='task',
            name='model',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('0', 'Running'), ('1', 'Occupied'), ('2', 'Vacant'), ('3', 'Offline')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='user_dataset',
            name='Dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.dataset'),
        ),
        migrations.AddField(
            model_name='user_dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.user'),
        ),
    ]
