# Generated by Django 3.2 on 2023-07-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_alter_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
