# Generated by Django 3.2 on 2023-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_alter_user_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='GPU_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='OS',
            field=models.CharField(choices=[('1', 'Windows'), ('2', 'Linux'), ('3', 'macOS'), ('4', 'iOS'), ('5', 'Android')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='RAM',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ROM',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='max_bandwidth',
            field=models.IntegerField(null=True),
        ),
    ]
