# Generated by Django 3.2 on 2023-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20230707_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_server',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='IP',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
