# Generated by Django 3.2 on 2023-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='size',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='graph_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_graph',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='total_size',
            field=models.IntegerField(null=True),
        ),
    ]
