# Generated by Django 3.2 on 2023-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0010_auto_20230713_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
